# Generated by Django 4.1.7 on 2023-02-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('notice', 'Notice'), ('result', 'Result')], max_length=10)),
                ('file_path', models.FileField(upload_to='fetched_data/%Y/%m/%d/')),
            ],
        ),
    ]
