# Generated by Django 4.1.7 on 2023-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetcheddata',
            name='url',
            field=models.URLField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
