# Generated by Django 4.1.7 on 2023-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_fetcheddata_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('BCT', 'BCT'), ('BEX', 'BEX'), ('BCE', 'BCE')], max_length=5)),
                ('year', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=5)),
                ('part', models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=5)),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='fetcheddata',
            name='is_ocr_read',
            field=models.BooleanField(default=False),
        ),
    ]
