# Generated by Django 4.1.7 on 2023-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_resultdata_fetcheddata_is_ocr_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bs_year', models.IntegerField()),
                ('faculty', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resultdata',
            name='bs',
            field=models.IntegerField(default=2079),
            preserve_default=False,
        ),
    ]
