# Generated by Django 4.1.7 on 2023-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_subscriber_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='symbol',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='part',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=5),
        ),
    ]
