# Generated by Django 4.1.7 on 2023-03-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_subscriber_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='faculty',
            field=models.CharField(choices=[('BCT', 'BCT'), ('BEX', 'BEX'), ('BCE', 'BCE')], max_length=5),
        ),
    ]
