# Generated by Django 4.1.7 on 2023-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_fetcheddata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='resultdata',
            unique_together={('faculty', 'bs', 'year', 'part')},
        ),
    ]
