# Generated by Django 4.1.7 on 2023-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_resultdata_symbol_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultdata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='resultdata',
            unique_together={('faculty', 'bs', 'year', 'part', 'symbol')},
        ),
    ]
